mysite/ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    #extra Funktion def stream_file in views, um Bild zu laden
    #diese URL sieht man, wenn man auf das Bild klickt
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/artist/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'artist'
urlpatterns = [
    path('', views.gallery, name='all'),
    #path('artist/<int:pk>/', views.ArtistDetailView.as_view(), name='artist_detail'),
    path('add/', views.addPhoto, name='add'),
    path('photo/<int:pk>/', views.viewPhoto, name='photo'),

    path('test/', views.ArtistListView.as_view(), name='test_artist_list'),
    path('test/artist/<int:pk>', views.ArtistDetailView.as_view(), name='test_artist_detail'),
    path('test/artist/create',
        views.ArtistCreateView.as_view(success_url=reverse_lazy('artist:test_artist_list')), name='test_artist_create'),
    path('test/artist/<int:pk>/update',
        views.ArtistUpdateView.as_view(success_url=reverse_lazy('artist:test_artist_list')), name='test_artist_update'),
    path('test/artist/<int:pk>/delete',
        views.ArtistDeleteView.as_view(success_url=reverse_lazy('artist:test_artist_list')), name='test_artist_confirm_delete'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView
from django.views import View, generic
from django.contrib.auth import views as auth_views

from django.contrib.auth import views

urlpatterns = [
    #path('', include('home.urls')),  # Change to ads.urls - meine echte Startseite is blog.urls
    #Ich möchte doch meine Blog-Auflistung als Homepage benutzen
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),

    # Sample applications
    # nix mehr synkyndineo nennen, nur noch als Link im html, aber nicht
    # mehr als App. Die App soll business heißen, irgendwo hat sich was mit den
    # synkyndineo-tables verhakelt
    #path('synkyndineo/', include('synkyndineo.urls')),
    path('home/', include('home.urls')),
    path('hello/', include('hello.urls')),
    path('authz/', include('authz.urls')),
    #path('', TemplateView.as_view(template_name='home/main.html')),
    path('polls/', include('polls.urls')),
    path('dataproject/', include('dataproject.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('samples/', include('samples.urls')),
    path('ads/', include('ads.urls')),
    path('artist/', include('artist.urls')),
    path('photos/', include('photos.urls')),
    path('smallads/', include('smallads.urls')),
    path('votes/', include('votes.urls')),
    #path('users/', include('users.urls')),
    #path('tracks/', include('tracks.urls')),
    #path('views/', include('views.urls')),
    #path('route/', include('route.urls', namespace='nsroute')),
    #path('tmpl/', include('tmpl.urls')),
    #path('gview/', include('gview.urls')),
    #path('session/', include('session.urls')),
    #path('getpost/', include('getpost.urls')),
    #path('form/', include('form.urls')),
    #path('crispy/', include('crispy.urls')),
    #path('myarts/', include('myarts.urls')),
    #path('menu/', include('menu.urls')),
    #path('forums/', include('forums.urls')),
    #path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    #path('favsql/', include('favsql.urls')),
    #path('rest/', include('rest.urls')),
    #path('usermodel/', include('usermodel.urls')),
    path('chat/', include('chat.urls')),
    #path('util/', include('util.urls')),
    #path('well/', include('well.urls')),
    #path('tagme/', include('tagme.urls')),
]


# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Up two folders to serve "site" content
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'static'),
        }
    ),
]

urlpatterns += [
    path('apple-touch-icon.png', serve, {
            'path': 'apple-touch-icon.png',
            'document_root': os.path.join(BASE_DIR, 'static'),
        }
    ),
]

# static-function macht, dass ich alle Bilder direkt im Browser durch diese
# Eingabe finde: seidelma.pythonanywhere.com/images/foobar.jpg (Amanda.jpg i. e.)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Switch to social login if it is configured - Keep for later

try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/photos/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'photos'
urlpatterns = [
    path('', views.gallery, name='gallery'),
    path('add/', views.addPhoto, name='add'),
    path('photo/<int:pk>/', views.viewPhoto, name='photo'),
    path('photo/<int:pk>/favorite',
        views.AddPhotoFavoriteView.as_view(), name='photo_favorite'),
    path('photo/<int:pk>/unfavorite',
        views.DeletePhotoFavoriteView.as_view(), name='photo_unfavorite'),
]

mysite/artist/models.py
from django.db import models

from django.template.defaultfilters import slugify
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings

from taggit.managers import TaggableManager


class Artist(models.Model):
    artist_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='artist_owner')
    name = models.CharField('Name', max_length=200)
    bio = models.TextField(max_length=5000, null=True, blank=True)

    profpic = models.ImageField(upload_to='artist_profpic', verbose_name='Profile Pic', null=True, blank=True) #Verbose_name ist für admin-Panel-Beschriftung
    #den Bilderupload über Images lösen - DRY!
    artist_image = models.ImageField(upload_to='artist_images', verbose_name='Image 1', null=True, blank=True)
    artist_image_2 = models.ImageField(upload_to='artist_images', verbose_name='Image 2', null=True, blank=True)
    artist_image_3 = models.ImageField(upload_to='artist_images', verbose_name='Image 3', null=True, blank=True)
    artist_altattr = models.CharField('Alt Attribut', max_length=200, null=True, blank=True, default=name)
    artist_image_description = models.TextField(max_length=500, default=artist_altattr, null=True, blank=True)

    poem1 = models.TextField(null=True, blank=True)
    poem2 = models.TextField(null=True, blank=True)
    poem3 = models.TextField(null=True, blank=True)

    email = models.EmailField(max_length=254, null=True, blank=True)

    artist_comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='ArtistComment',
                related_name='artist_comments_owned')

    artist_favorites = models.ManyToManyField(settings.AUTH_USER_MODEL, through='ArtistFav',
                related_name='artist_favorite_artists')

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    def __str__(self):
        return self.name


class ArtistCategory(models.Model):
    # darf ein Artist mehrere Kategorien haben???
    # ja - hier auch die Möglichkeit von CHOICES einbauen und Neuanlage
    catname = models.CharField('Category', max_length=200)

    tags = TaggableManager()

    def __str__(self):
        return self.catname


def get_image_filename(instance, filename):
    name = instance.artist.name
    slug = slugify(name)
    return "artist_images/%s-%s" % (slug, filename)
    #upload_to=get_image_filename, das ist ein cooler hack, um über die Funktion im imageField ein Bild zu bezeichen und upzuloaden


class Images(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, default=None)
    # es klappt in media upzuloaden ohne das ImageField zu alterieren, die Bilder
    # landen in media, weil es so in den Settings steht, nun muss ich mir noch
    # eine Lösung überlegen, wie ich in media einen Ordner artist reinbekomme
    # Update: Lösung ist einfach über upload_to einen Unterordner erschaffen, wenn
    # MEDIA_ROOT und MEDIA_URL in den settings gesetzt sind

    image = models.ImageField(upload_to='artist_images', verbose_name='Image')
    altattr = models.CharField('Alt Attribut', max_length=200, null=True, blank=True, default=artist)
    description = models.TextField(max_length=500, default=altattr, null=True, blank=True)

    def __str__(self):
        if len(self.description) < 20:
            return self.description
        return self.description[:16] + ' ...'


class Article(models.Model):
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()
    pic = models.ImageField(upload_to='artist_articles', null=True, blank=True)
    price = models.FloatField()
    size = models.CharField(max_length=100, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title


class ArtistComment(models.Model):
    text = models.TextField(validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")])
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 30 : return self.text
        return self.text[:27] + ' ...'


class ArtistFav(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # siehe docs.djangoproject.com/en/2.1/ref/models/options/#unique-together
    '''
    Use UniqueConstraint with the constraints option instead.

    UniqueConstraint provides more functionality than unique_together.
    unique_together may be deprecated in the future.
    '''
    class Meta:
        unique_together = ('artist', 'user')

    def __str__(self):
        return '%s likes %s'%(self.user.username, self.artist.name[:10])

mysite/photos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Photo, PhotoFav, PhotoComment
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from django.views import View
from django.urls import reverse_lazy, reverse


from django.http import HttpResponse

from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

'''
# login/logout pages hatte ich schon für andere apps gebaut
def loginUser(request):
    page = 'login'
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('gallery')

    return render(request, 'photos/login_register.html', {'page': page})


def logoutUser(request):
    logout(request)
    return redirect('login')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            if user is not None:
                login(request, user)
                return redirect('gallery')

    context = {'form': form, 'page': page}
    return render(request, 'photos/login_register.html', context)
'''

# view gallery ist so geschrieben, dass nur der reg. und eingeloggte User
# ausschließlich SEINE Kategorien und entsprechenden Fotos sieht
# nicht eingeloggte Betrachter sehen nicht einmal die Photoapp
# eingeloggte User (auch über github) sehen nichts außer ihre eigenen Uploads
'''
Für die Sellwerk-Kleinanzeigen muss ich es aber so schreiben, dass alle user
alle Anzeigen sehen können!
'''

@login_required(login_url='login')
def gallery(request):
    # der eingeloggte user wird angefragt
    user = request.user
    category = request.GET.get('category')
    # es gibt einen bug - wenn ich als User ein Foto ohne Kategorie hochlade, dann
    # ist es nicht sichtbar :(
    # ohne Kategorie kann ich es in admin auch nicht anklicken :(
    if category == None:
        photos = Photo.objects.filter(category__user=user)
    else:
        photos = Photo.objects.filter(
            category__name__contains=category, category__user=user)

    favorites = []
    if request.user.is_authenticated:
        '''
        related_name='favorite_ads' aus model AD
        rows = [{'id': 2}] (A list of rows)
        '''
        rows = request.user.favorite_photos.values('id')
        favorites = [ row['id'] for row in rows]

    categories = Category.objects.filter(user=user)
    ctx = {'categories': categories, 'photos': photos, 'favorites': favorites}
    return render(request, 'photos/gallery.html', ctx)


@login_required(login_url='login')
def viewPhoto(request, pk):
    photo = Photo.objects.get(id=pk)
    ctx = {'photo': photo}
    return render(request, 'photos/photo.html', ctx)


@login_required(login_url='login')
def addPhoto(request):
    user = request.user

    categories = user.category_set.all()

    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images')
        '''
        das ist die Lösung: nimm kein modelform,
        bestimme erst einmal welche variable category,
        dann create unten das object smalladd mit category= category
        '''
        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(
                user=user,
                name=data['category_new'])
        else:
            category = None

        for image in images:
            photo = Photo.objects.create(
                category=category,
                description=data['description'],
                image=image,
            )

        return redirect('photos:gallery')

    ctx = {'categories': categories}
    return render(request, 'photos/add.html', ctx)


# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddPhotoFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print('Photo pk', pk)
        a = get_object_or_404(Photo, id=pk)
        fav = PhotoFav(user=request.user, photo=a)
        try:
            fav.save() #In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeletePhotoFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print('Delete pk', pk)
        a = get_object_or_404(Photo, id=pk)
        try:
            fav = PhotoFav.objects.get(user=request.user, photo=a).delete()
        except PhotoFav.DoesNotExist as e:
            pass
        return HttpResponse()

mysite/artist/templates/artist/artist_detail.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Our artists - {{ artist.name }}{% endblock %}

{% block head %}
<style>
* {
  box-sizing: border-box;
}

img {
  vertical-align: middle;
}

/* Position the image container (needed to position the left and right arrows) */
.container {
  position: relative;
}

/* Hide the images by default */
.mySlides {
  display: none;
}

/* Add a pointer when hovering over the thumbnail images */
.cursor {
  cursor: pointer;
}

/* Next & previous buttons */
.prev,
.next {
  cursor: pointer;
  position: absolute;
  top: 40%;
  width: auto;
  padding: 16px;
  margin-top: -50px;
  color: white;
  font-weight: bold;
  font-size: 20px;
  border-radius: 0 3px 3px 0;
  user-select: none;
  -webkit-user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover,
.next:hover {
  background-color: rgba(0, 0, 0, 0.5);
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* Container for image text */
.caption-container {
  text-align: center;
  background-color: #222;
  padding: 2px 16px;
  color: white;
}

.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Six columns side by side */
.column {
  float: left;
  width: 25%;
}

/* Add a transparency effect for thumnbail images */
.demo {
  opacity: 0.6;
}

.active,
.demo:hover {
  opacity: 1;
}
</style>
{% endblock %}

{% block content %}

<div class="container">


    <span style="float: right;">
    ({{ artist.updated_at|naturaltime }})
    {% if artist.owner == user %}
    <a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
    <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
    </span>

    <h1 class="herotitle">{{ artist.name }}</h1>

    <!-- Container for the image gallery -->


    <!-- Full-width images with number text -->
    <div class="mySlides">
        <div class="numbertext">1 / 6</div>
            <img src="{{ artist.profpic.url }}" style="width:50%;
            display: block; margin: 0 auto;">
    </div>

    <div class="mySlides">
        <div class="numbertext">2 / 6</div>
            <img src="{{ artist.artist_image.url }}" style="width:50%;
            display: block; margin: 0 auto;">
    </div>

    <div class="mySlides">
        <div class="numbertext">3 / 6</div>
            <img src="{{ artist.artist_image_2.url }}" style="width:50%;
            display: block; margin: 0 auto;">
    </div>

    <div class="mySlides">
        <div class="numbertext">4 / 6</div>
            <img src="{{ artist.artist_image_3.url }}" style="width:50%;
            display: block; margin: 0 auto;">
    </div>


    <!-- Next and previous buttons -->
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    <!-- Image text -->
     <div class="caption-container">
        <p id="caption"></p>
    </div>

    <!-- Thumbnail images -->
    <div class="row">
        <div class="column">
          <img class="demo cursor" src="{{ artist.profpic.url }}" style="width:100%" onclick="currentSlide(1)" alt="{{ artist.name }}">
        </div>
        <div class="column">
          <img class="demo cursor" src="{{ artist.artist_image.url }}" style="width:100%" onclick="currentSlide(2)" alt="{{ artist.altattr }}">
        </div>
        <div class="column">
          <img class="demo cursor" src="{{ artist.artist_image_2.url }}" style="width:100%" onclick="currentSlide(3)" alt="{{ artist.altattr }}">
        </div>
        <div class="column">
          <img class="demo cursor" src="{{ artist.artist_image_3.url }}" style="width:100%" onclick="currentSlide(4)" alt="{{ artist.altattr }}">
        </div>
    </div>

<script>
var slideIndex = 1;
showSlides(slideIndex);

// Next/previous controls
function plusSlides(n) {
  showSlides(slideIndex += n);
}

// Thumbnail image controls
function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>
    <div>
        <h5><center>{{ artist.bio }}</center></h5>
    </div>

    <span>{{ artist.email }}</span>

    <!-- tags hier einbauen -->
    {% if artist.tags.all %}
    {% for tag in artist.tags.all %}
        <!--Minimalvariante - eigentlich sollten die klickbar sein und irgendwas machen - aber was???? ;-)
        zu erst einmal in die Suche einbauen-->
        <span style="border:1px grey solid; background-color: Teal;">{{ tag }}</span>
    {% endfor %}
    {% endif %}
    <p>
    <a href="{% url 'artist:all' %}">All Artists</a>
    </p>
    <div class="row"><hr></div>
</div>
{% endblock %}

mysite/artist/templates/artist/artist_main_list.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Gallery of our Artists - {{ title }}{% endblock %}


{% block head %}
<style>
    .image-thumbnail {
        height: 200px;
        object-fit: cover;
    }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <h1 class="herotitle">Gallery - our Artists</h1>

    <div class="m-5">
    <div class="row">
        <div class="col-md-3">

            <div class="card my-2">
                <div class="card-header">
                    Categories
                </div>
                  <ul  class="list-group list-group-flush">
                    <li class="list-group-item"><a href="{% url 'artist:all' %}">All</a></li>
                    {% for artist in artists %}
                        <li class="list-group-item">
                            <a href="{% url 'artist:all' %}?artist={{ artist.name }}">{{ artist.name }}</a>
                        </li>
                    {% endfor %}

                    <li class="list-group-item">
                        <a href="{% url 'artist:add' %}" class="btn btn-dark btn-block btn-sm m-1">Add Artist</a>
                    </li>
                  </ul>
            </div>

        </div>

        <div class="col-md-9">
            <div class="row">
                {% for photo in photos %}
                <div class="col-md-4">
                <div class="card my-2">
                    <img class="image-thumbnail" src="{{ photo.image.url }}" class="card-img-top" alt="{{ photo.altattr }}">
                        <div class="card-body">
                            <small>{{ photo.artist.name }}</small>
                        </div>
                        <a href="{% url 'artist:photo' photo.id %}" class="btn btn-outline-dark btn-sm m-1">View Photo...</a>

                </div>
                </div>
                {% empty %}
                    <p>No Photos in the Database</p>
                {% endfor %}

            </div>
        </div>
    </div>

    </div>
</div>
{% endblock %}

mysite/artist/templates/artist/photo.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Photos of Artists - {{ title }}{% endblock %}


{% block head %}
<style>

</style>
{% endblock %}

{% block content %}

<div class="container">
    <h1 class="herotitle">Photos</h1>

    <div class="m-5"></div>
    <div class="row justify-content-center">
        <div class="col">
            <a href="{% url 'artist:all' %}" class="btn btn-dark my-3">Go Back</a>
            <div style="height: 90vh;">
                <img style="max-width: 100%; max-height: 100%;" src="{{ photos.image.url }}" alt="{{ altattr }}">
                <p>{{ photos.description }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/artist/templates/artist/test_artist_list.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Test Artist Main List{% endblock %}

{% block head %}
<style>
    .image-thumbnail {
        height: 200px;
        object-fit: cover;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="herotitle">Gallery - Our Artists</h1>

    <div class="m-5">
    <div class="row">
        <div class="col-md-3">
            <div class="card my-2">
              <div class="card-header">
                Categories
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'artist:all' %}">All</a>
                </li>
                {% for category in categories %}
                    <li class="{% url 'artist:all' %}?artist={{ artist.name }}">{{ category.name }}</li>
                {% empty %}
                    <p>No categories yet...</p>
                {% endfor %}
                <a href="#" class="btn btn-dark btn-block btn-sm m-1">Add Artist</a>
                <a href="#" class="btn btn-dark btn-block btn-sm m-1">xyz</a>
              </ul>
            </div>
        </div>

        <div class="col-md-9">
            <div class="row">
                {% for artist in artist_list %}
                <div class="col-md-4">
                <div class="card my-2">
                    <img class="image-thumbnail" src="{{ artist.profpic.url }}" class="card-img-top" alt="{{ artist.altattr }}">
                        <div class="card-body">
                            <small>{{ artist.name }}</small>
                        </div>
                        <a href="{% url 'artist:test_artist_detail' artist.id %}" class="btn btn-outline-dark btn-sm m-1">View Artist...</a>

                </div>
                </div>
                {% empty %}
                    <p>No Artists in the Database</p>
                {% endfor %}

            </div>
        </div>

        <div class="col-md-1"></div>

    </div>
    </div>


</div>
{% endblock %}