mysite/ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    #extra Funktion def stream_file in views, um Bild zu laden
    #diese URL sieht man, wenn man auf das Bild klickt
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView
from django.views import View, generic
from django.contrib.auth import views as auth_views

from django.contrib.auth import views

urlpatterns = [
    #path('', include('home.urls')),  # Change to ads.urls - meine echte Startseite is blog.urls
    #Ich möchte doch meine Blog-Auflistung als Homepage benutzen
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),

    # Sample applications
    # nix mehr synkyndineo nennen, nur noch als Link im html, aber nicht
    # mehr als App. Die App soll business heißen, irgendwo hat sich was mit den
    # synkyndineo-tables verhakelt
    #path('synkyndineo/', include('synkyndineo.urls')),
    path('home/', include('home.urls')),
    path('hello/', include('hello.urls')),
    path('authz/', include('authz.urls')),
    #path('', TemplateView.as_view(template_name='home/main.html')),
    path('polls/', include('polls.urls')),
    path('dataproject/', include('dataproject.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('samples/', include('samples.urls')),
    path('ads/', include('ads.urls')),
    path('artist/', include('artist.urls')),
    path('photos/', include('photos.urls')),
    path('smallads/', include('smallads.urls')),
    path('votes/', include('votes.urls')),
    #path('users/', include('users.urls')),
    #path('tracks/', include('tracks.urls')),
    #path('views/', include('views.urls')),
    #path('route/', include('route.urls', namespace='nsroute')),
    #path('tmpl/', include('tmpl.urls')),
    #path('gview/', include('gview.urls')),
    #path('session/', include('session.urls')),
    #path('getpost/', include('getpost.urls')),
    #path('form/', include('form.urls')),
    #path('crispy/', include('crispy.urls')),
    #path('myarts/', include('myarts.urls')),
    #path('menu/', include('menu.urls')),
    #path('forums/', include('forums.urls')),
    #path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    #path('favsql/', include('favsql.urls')),
    #path('rest/', include('rest.urls')),
    #path('usermodel/', include('usermodel.urls')),
    path('chat/', include('chat.urls')),
    #path('util/', include('util.urls')),
    #path('well/', include('well.urls')),
    #path('tagme/', include('tagme.urls')),
]


# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Up two folders to serve "site" content
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'static'),
        }
    ),
]

urlpatterns += [
    path('apple-touch-icon.png', serve, {
            'path': 'apple-touch-icon.png',
            'document_root': os.path.join(BASE_DIR, 'static'),
        }
    ),
]

# static-function macht, dass ich alle Bilder direkt im Browser durch diese
# Eingabe finde: seidelma.pythonanywhere.com/images/foobar.jpg (Amanda.jpg i. e.)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Switch to social login if it is configured - Keep for later

try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/ads/forms.py
from django import forms
from .models import Ad
from django.core.files.uploadedfile import InMemoryUploadedFile
from .humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Ad
        fields = ['title', 'text', 'picture', 'price', 'tags']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()

        return instance

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):  #muss das nicht Modelform heißen?
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

mysite/ads/views.py
from ads.models import Ad, Comment, Fav
from django.views import View
from ads.owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse

from django.db.models import Q

from ads.forms import CreateForm, CommentForm

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.humanize.templatetags.humanize import naturaltime

from ads.utils import dump_queries


class AdListView(OwnerListView):
    model = Ad
    # in der urls.py heißt dieser view "all"
    # By convention:
    template_name = "ads/ad_list.html"

    def get(self, request):
        # mit der Suche beginnen
        strval = request.GET.get("search", False)
        if strval:
            # Simple title-only search
            # objects = Ad.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            query.add(Q(tags__name__icontains=strval), Q.OR)
            ad_list = Ad.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            ad_list = Ad.objects.all().order_by('-updated_at')[:10]

        favorites = []
        if request.user.is_authenticated:
            '''
            related_name='favorite_ads' aus model AD
            rows = [{'id': 2}] (A list of rows)
            '''
            rows = request.user.favorite_ads.values('id')
            favorites = [ row['id'] for row in rows]

        # Augment the ad_list
        for obj in ad_list:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = { 'ad_list': ad_list, 'favorites': favorites, 'search': strval}
        return render(request, self.template_name, ctx)

# References

# https://docs.djangoproject.com/en/3.0/topics/db/queries/#one-to-many-relationships

# Note that the select_related() QuerySet method recursively prepopulates the
# cache of all one-to-many relationships ahead of time.

# sql “LIKE” equivalent in django query
# https://stackoverflow.com/questions/18140838/sql-like-equivalent-in-django-query

# How do I do an OR filter in a Django query?
# https://stackoverflow.com/questions/739776/how-do-i-do-an-or-filter-in-a-django-query

# https://stackoverflow.com/questions/1074212/how-can-i-see-the-raw-sql-queries-django-is-running

'''
class AdListView(OwnerListView):
    model = Ad
    # in der urls.py heißt dieser view "all"
    # By convention:
    template_name = "ads/ad_list.html"

    def get(self, request):
        ad_list = Ad.objects.all()
        favorites = []
        if request.user.is_authenticated:
'''
'''
            related_name='favorite_ads' aus model AD
            rows = [{'id': 2}] (A list of rows)
'''
'''
            rows = request.user.favorite_ads.values('id')
            favorites = [ row['id'] for row in rows]
        ctx = { 'ad_list': ad_list, 'favorites': favorites}
        return render(request, self.template_name, ctx)
'''



class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "ads/ad_detail.html"

    #in diese comment get-request muss natürlich auch noch meine Bilderrequest rein,
    #da diese def get die OwnerDetailView überschreibt

    def get(self, request, pk):
        ad = Ad.objects.get(id=pk)
        comments = Comment.objects.filter(ad=ad).order_by('-updated_at')
        comment_form = CommentForm()
        ctx = {'ad' : ad, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, ctx)



'''
(3) Take a look at pics/views.py and adapt the patterns in PicCreateView and
PicUpdateView and replace the code for AdCreateView and AdUpdateView in ads/views.py.
These new views don't inherit from owner.py because they manage the owner
column in the get() and post() methods.

Ich schreibe also Teile aus owner.py wieder zurück in diese Views. Für folgende
Projekte merken, dass ich eigentlich auch alles in owner.py händeln kann, oder?
'''

class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')   #einfach nur der AdListView

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()    # Add this
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=ad)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.save()
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()    # Add this

        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        ad = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=ad)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])


def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response

# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print('Add pk', pk)
        a = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=a)
        try:
            fav.save() #In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print('Delete pk', pk)
        a = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=a).delete()
        except Fav.DoesNotExist as e:
            pass
        return HttpResponse()

mysite/ads/templates/ads/ad_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h1>Delete Classified</h1>

<p>Are you sure you want to delete the ad {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
</div>
{% endblock %}

mysite/ads/templates/ads/ad_detail.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Classifieds - {{ ad.title }}{% endblock %}

{% block content %}
<div class="container">

{% if ad.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';">
    <img style="width:50%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
</div>
{% endif %}

<span style="float: right;">
({{ ad.updated_at|naturaltime }})
{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ ad.title }}</h1>

{% if ad.content_type %}
<img style="float:right; max-width:25%;" src="{% url 'ads:ad_picture' ad.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}

<ul>
    <li>{{ ad.text }}</li>
    <li>{{ ad.price }} Euro</li>
</ul>

<!-- tags hier einbauen -->
{% if ad.tags.all %}
{% for tag in ad.tags.all %}
    <!--Minimalvariante - eigentlich sollten die klickbar sein und irgendwas machen - aber was???? ;-)
    zu erst einmal in die Suche einbauen-->
    <span style="border:1px grey solid; background-color: Teal;">{{ tag }}</span>
{% endfor %}
{% endif %}

{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
</form>
</p>
{% endif %}

{% for comment in comments %}
<p>{{ comment.owner }}: {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'ads:comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}

<p>
</p>
<p>
<a href="{% url 'ads:all' %}">All Classifieds</a>
</p>
</div>
{% endblock %}

mysite/ads/templates/ads/ad_detail_old_klappt.html
{% extends 'base_menu.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background into light grey*/
}
</style>
{% endblock %}

{% block content %}
<div class="container">

{% if ad.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';">
    <img style="width:50%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
</div>
{% endif %}

<span style="float: right;">
({{ ad.updated_at|naturaltime }})
{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ ad.title }}</h1>

{% if ad.content_type %}
<img style="float:right; max-width:25%;" src="{% url 'ads:ad_picture' ad.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}

<ul>
    <li>{{ ad.text }}</li>
    <li>{{ ad.price }} Euro</li>
</ul>

{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
</form>
</p>
{% endif %}

{% for comment in comments %}
<p>{{ comment.owner }}: {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'ads:comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}

<p>
</p>
<p>
<a href="{% url 'ads:all' %}">Alle Kleinanzeigen</a>
</p>
</div>
{% endblock %}

mysite/ads/templates/ads/ad_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>

<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->

<script>
$("#upload_form").submit(function() {
    console.log('Checking file size');
    if (window.File && window.FileReader && window.FileList && window.Blob) {
        var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
        if file && file.size > {{ form.max_upload_limit }} ) {
            alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
        return false;
        }
    }
});
</script>
</div>
{% endblock %}

mysite/ads/templates/ads/ad_list.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
<style>
    * {
        box-sizing: border-box;
    }
    form.ad_list_search_form input[type=text] {
      padding: 10px;
      font-size: 17px;
      border: 1px solid teal;
      float: left;
      width: 80%;
      background: #f1f1f1;
    }

    form.ad_list_search_form button {
      float: left;
      width: 20%;
      padding: 10px;
      background: #2196F3;
      color: white;
      font-size: 17px;
      border: 1px solid teal;
      border-left: none;
      cursor: pointer;
    }

    form.ad_list_search_form button:hover {
      background: #0b7dda;
    }

    form.ad_list_search_form::after {
      content: "";
      clear: both;
      display: table;
    }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <h1>Classifieds</h1>
<!--
    <div style="float:right">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp-->
<!--    <form class="ad_list_search_form">
        <input type="text" placeholder="Search.." name="search" pattern=".{3,}"  required title="3 characters minimum"
        {% if search %} value="{{ search }}" {% endif %}>
        <button type="submit"><i class="fa fa-search"></i></button>
        <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
    </form>
    </div>
-->
    <p>
    {% if ad_list %}
    <ul>
      {% for ad in ad_list %}
        <li>
            <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
            {% if ad.owner == user %}
            (<a href="{% url 'ads:ad_update' ad.id %}">Ändern</a> |
            <a href="{% url 'ads:ad_delete' ad.id %}">Löschen</a>)
            {% endif %}
            {% if user.is_authenticated %}
            <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                <a href="#" onclick=
                    "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} ); return false;"
                    {% if ad.id not in favorites %} style="display: none;" {% endif %}
                    id="favorite_star_{{ ad.id }}">
                <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
                </a>
                <!-- the second href -->
                <!-- Weird - fa-stack changes vertical spacing so to be consistent we use it here -->
                <a href="#" onclick=
                    "favPost('{% url 'ads:ad_favorite'  ad.id %}', {{ ad.id }} ); return false;"
                    {% if ad.id in favorites %} style="display: none;" {% endif %}
                    id="unfavorite_star_{{ ad.id }}">
                <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
                </a>
            {% endif %}
        </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no classifieds in the database.</p>
    {% endif %}
    </p>
    <p>
    <a href="{% url 'ads:ad_create' %}">Create Ad</a> |
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
    {% endif %}
    </p>

    <!--script hier ist ein bug drin: siehe console, es lässt sich nicht anklicken (Edit: ich habe in den console.log parms + statt Komma eingefügt>
        function favPost(url, ad_id) {
            fetch(url, {
                method: "POST", // *GET, POST, DELETE, PUT, etc.
                mode: "cors", // no-cors, cors, *same-origin
                cache: "no-cache", // default, no-cache, reload, force-cache, only-if-cached
                credentials: "same-origin", // include, *same-origin, omit
                headers: {
                    "Content-type": "application/x-www-form-urlencoded",
                },
                redirect: "follow", // manual, *follow, error
                referrer: "no-referrer", // no-referrer, *client
            }).then(function(data) {
                console.log(url + 'finished');
                $("#unfavorite_star_"+ad_id).toggle();
                $("#favorite_star_"+ad_id).toggle();
            }.catch(function() {
                console.log(url + 'error');
            });
        }
    </script-->

    <script>
    function favPost(url, ad_id) {
        console.log('Requesting JSON');
        $.post(url, {},  function(rowz){
            console.log(url, 'finished');
            $("#unfavorite_star_"+ad_id).toggle();
            $("#favorite_star_"+ad_id).toggle();
        }).fail(function(xhr) {
            alert('Url failed with '+xhr.status+' '+url);
        });
    }
    </script>

</div>
{% endblock %}

mysite/ads/templates/ads/comment_delete.html
{% extends "base.html" %} <!--extends "base_bootstrap.html"-->
{% block content %}
<div class="container">

<h1>Delete Comment</h1>

<p>Are you sure you want to delete comment:</p>
<p>"{{ comment.text }}"?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
</form>

</div>
{% endblock %}