mysite/ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    #extra Funktion def stream_file in views, um Bild zu laden
    #diese URL sieht man, wenn man auf das Bild klickt
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView
from django.views import View, generic
from django.contrib.auth import views as auth_views

from django.contrib.auth import views

urlpatterns = [
    #path('', include('home.urls')),  # Change to ads.urls - meine echte Startseite is blog.urls
    #Ich möchte doch meine Blog-Auflistung als Homepage benutzen
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),

    # Sample applications
    # nix mehr synkyndineo nennen, nur noch als Link im html, aber nicht
    # mehr als App. Die App soll business heißen, irgendwo hat sich was mit den
    # synkyndineo-tables verhakelt
    #path('synkyndineo/', include('synkyndineo.urls')),
    path('home/', include('home.urls')),
    path('hello/', include('hello.urls')),
    path('authz/', include('authz.urls')),
    #path('', TemplateView.as_view(template_name='home/main.html')),
    path('polls/', include('polls.urls')),
    path('dataproject/', include('dataproject.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('samples/', include('samples.urls')),
    path('ads/', include('ads.urls')),
    path('artist/', include('artist.urls')),
    path('photos/', include('photos.urls')),
    path('smallads/', include('smallads.urls')),
    path('votes/', include('votes.urls')),
    #path('users/', include('users.urls')),
    #path('tracks/', include('tracks.urls')),
    #path('views/', include('views.urls')),
    #path('route/', include('route.urls', namespace='nsroute')),
    #path('tmpl/', include('tmpl.urls')),
    #path('gview/', include('gview.urls')),
    #path('session/', include('session.urls')),
    #path('getpost/', include('getpost.urls')),
    #path('form/', include('form.urls')),
    #path('crispy/', include('crispy.urls')),
    #path('myarts/', include('myarts.urls')),
    #path('menu/', include('menu.urls')),
    #path('forums/', include('forums.urls')),
    #path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    #path('favsql/', include('favsql.urls')),
    #path('rest/', include('rest.urls')),
    #path('usermodel/', include('usermodel.urls')),
    path('chat/', include('chat.urls')),
    #path('util/', include('util.urls')),
    #path('well/', include('well.urls')),
    #path('tagme/', include('tagme.urls')),
]


# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Up two folders to serve "site" content
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'static'),
        }
    ),
]

urlpatterns += [
    path('apple-touch-icon.png', serve, {
            'path': 'apple-touch-icon.png',
            'document_root': os.path.join(BASE_DIR, 'static'),
        }
    ),
]

# static-function macht, dass ich alle Bilder direkt im Browser durch diese
# Eingabe finde: seidelma.pythonanywhere.com/images/foobar.jpg (Amanda.jpg i. e.)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Switch to social login if it is configured - Keep for later

try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/smallads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'smallads'
urlpatterns = [
    path('', views.SmalladListView.as_view(), name='all'),
    path('smallad/<int:pk>', views.SmalladDetailView.as_view(), name='smallad_detail'),
    path('smallad/create',
        views.SmalladCreateView.as_view(success_url=reverse_lazy('smallads:all')), name='smallad_create'),
    path('smallad/<int:pk>/update',
        views.SmalladUpdateView.as_view(success_url=reverse_lazy('smallads:all')), name='smallad_update'),
    path('smallad/<int:pk>/delete',
        views.SmalladDeleteView.as_view(success_url=reverse_lazy('smallads:all')), name='smallad_delete'),
    path('smallad/<int:pk>/comment',
        views.SmalladCommentCreateView.as_view(), name='smallad_comment_create'),
    path('comment/<int:pk>/delete',
        views.SmalladCommentDeleteView.as_view(success_url=reverse_lazy('smallads:all')), name='smallad_comment_delete'),
    path('smallad/<int:pk>/favorite',
        views.SmalladAddFavoriteView.as_view(), name='smallad_favorite'),
    path('smallad/<int:pk>/unfavorite',
        views.SmalladDeleteFavoriteView.as_view(), name='smallad_unfavorite'),
    path('favs',
        views.allFavs, name='smallad_allfavs'),
]

mysite/smallads/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.conf import settings

from taggit.managers import TaggableManager

# Create your models here.

class SmalladCategory(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    # SET_NULL: Set the reference to NULL (requires the field to be nullable).
    # For instance, when you delete a User, you might want to keep the comments
    # he posted on blog posts, but say it was posted by an anonymous (or deleted)
    # user. SQL equivalent: SET NULL.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, help_text = 'Enter a category (e. g. Home & Garden)',
        validators = [MinLengthValidator(3, 'Category must be greater than 2 characters')], null=False, blank=False)

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Smallad(models.Model):
    # erstmal pro Ad nur ein Foto - später über eine Schleife mehrere Fotos uploaden
    # aber nur ein image-Feld. Geht das???
    class Meta:
        verbose_name = 'Kleinanzeige'   #für die Admin Anzeige links im Menü
        verbose_name_plural = 'Kleinanzeigen'

    title = models.CharField(max_length=200,
            validators=[MinLengthValidator(3, "Title must be greater than 2 characters")])
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False, blank=False, related_name='smallad_owner')

    category = models.ForeignKey(
        SmalladCategory, on_delete=models.SET_NULL, null=True, blank=True)
    # für später zum Knobeln: Bilder werden nicht gelöscht, wenn smallad gelöscht wird
    image = models.ImageField(upload_to='smallads_images', verbose_name='Photopfad und -name', null=False, blank=False)
    description = models.TextField()
    smallad_comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='SmalladComment',
                related_name='comments_owned')

    smallad_favorites = models.ManyToManyField(settings.AUTH_USER_MODEL, through='SmalladFav',
                related_name='favorite_smallads')
    #kommende Zeile wird schon von smallad_favorites ausgedrückt
    #userUpVotes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='smalladUpVotes')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    def __str__(self):
        return self.title



class SmalladComment(models.Model):
    text = models.TextField(validators=[MinLengthValidator(4, "Comment must be greater than 3 characters")], null=True, blank=True)
    smallad = models.ForeignKey(Smallad, on_delete=models.CASCADE, null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'


class SmalladFav(models.Model):
    smallad = models.ForeignKey(Smallad, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='smallad_favs_users')
    #Alternative ausprobieren, damit jeder Visitor upvoten kann

    #smallad_visitor - also anonym - dann müssten die votes (siehe poll app) gesammelt werden und danach sortiert werden IDEE! :-)

    # siehe docs.djangoproject.com/en/2.1/ref/models/options/#unique-together
    '''
    Use UniqueConstraint with the constraints option instead.

    UniqueConstraint provides more functionality than unique_together.
    unique_together may be deprecated in the future.
    '''
    class Meta:
        unique_together = ('smallad', 'user')

    def __str__(self):
        return '%s likes %s'%(self.user.username, self.smallad.title[:20])

mysite/smallads/forms.py
from django import forms
from .models import Smallad


# Create the form class.
# benutze ich ersmal nicht, weil ich nicht weiß, wie ich overriden soll
# für später zum Knobeln: in docs - sind das initial values???
class CreateForm(forms.ModelForm):

    class Meta:
        model = Smallad
        fields = ['title', 'price', 'description', 'category', 'image', 'tags']

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        if commit:
            instance.save()
            self.save_m2m()

        return instance


# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):  #muss das nicht Modelform heißen?
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

mysite/smallads/templates/smallads/smallad_allfav.html
{% extends 'base.html' %}


{% block content %}


{% if smalladfav %}
    {% for fav in smalladfav %}
        <p>{{ fav.user }} -- {{ fav.id }} -- {{ fav.smallad }}</p>
    {% empty %}
        <p>Keine Favoriten</p>
    {% endfor %}
{% endif %}

{% endblock %}

mysite/smallads/templates/smallads/smallad_comment_delete.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Kleinanzeigen - {{ smallad.title }}{% endblock %}

{% block content %}
<div class="container">


<h1>{{ smallad.title }} Kommentar löschen</h1>


</div>
{% endblock %}

mysite/smallads/templates/smallads/smallad_confirm_delete.html
{% extends 'base.html' %}


{% block title %}Kleinanzeigen - {{ smallad.title }}{% endblock %}

{% block content %}
<div class="container-fluid">


<h1 class="herotitle">{{ smallad.title }} löschen</h1>

<p>Are you sure you want to delete the smallad {{ smallad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'smallads:all' %}';return false;">
</form>


</div>
{% endblock %}

mysite/smallads/templates/smallads/smallad_detail.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Kleinanzeigen - {{ smallad.title }}{% endblock %}

{% block head %}
<style>

    .image-thumbnail {
            height: 400px;
            object-fit: cover;
    }

    .list-group-item a {
            text-decoration: none;
            color: black;
    }
</style>
{% endblock %}

{% block content %}
<div class="m-5">
    <div class="container-fluid">


<div class="row justify-content-center">

<div class="col-md-8">
    <div class="row justify-content-center">
        <div class="card" style="width: 45rem;">
        <div class="card-header">
            <a href="{% url 'smallads:all' %}" class="btn btn-dark my-3">Go Back</a>
            <span style="float: right;">
                ({{ smallad.updated_at|naturaltime }})
                {% if smallad.owner == user %}
                <a href="{% url 'smallads:smallad_update' smallad.id %}"><i class="fa fa-pencil"></i></a>
                <a href="{% url 'smallads:smallad_delete' smallad.id %}"><i class="fa fa-trash"></i></a>
                {% endif %}
            </span>
        </div>
          <img class="image-thumbnail" src="{{smallad.image.url}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{ smallad.title }}</h5>
            <p class="card-text">{{ smallad.description }}</p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Preis: {{ smallad.price }} Euro</li>
            <li class="list-group-item">Tags:
            <!-- tags hier einbauen -->
                {% if smallad.tags.all %}
                {% for tag in smallad.tags.all %}
                    <!--Minimalvariante - eigentlich sollten die klickbar sein und irgendwas machen - aber was???? ;-)
                    zu erst einmal in die Suche einbauen-->
                    <span style="border:1px grey solid; background-color: Teal;">{{ tag }}</span>
                {% endfor %}
                {% endif %}
            </li>

           <!--hier die kleinen Sterne einbauen -->
            <!--2. Schritt: für alle user mit Klickfunktion - aber nur auf Detailseite-->

            {% if user.is_authenticated %}
            <li class="list-group-item">Mein Favorit:</li>
            <li class="list-group-item">

                                    <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                                    <a href="#" onclick=
                                        "favAd('{% url 'smallads:smallad_unfavorite' smallad.id %}', {{ smallad.id }} ); return false;"
                                        {% if smallad.id not in favorites %} style="display: none;" {% endif %}
                                        id="favorite_star_{{ smallad.id }}">
                                    <span class="fa-stack" style="vertical-align: middle;">
                                    <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                                    <i class="fa fa-star-o fa-stack-1x"></i>
                                    </span>
                                    </a>
                                    <!-- the second href -->
                                    <!-- Weird - fa-stack changes vertical spacing so to be consistent we use it here -->
                                    <a href="#" onclick=
                                        "favAd('{% url 'smallads:smallad_favorite' smallad.id %}', {{ smallad.id }} ); return false;"
                                        {% if smallad.id in favorites %} style="display: none;" {% endif %}
                                        id="unfavorite_star_{{ smallad.id }}">
                                    <span class="fa-stack" style="vertical-align: middle;">
                                    <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                                    <i class="fa fa-star-o fa-stack-1x"></i>
                                    </span>
                                    </a>
            </li>
            {% endif %}
            <li class="list-group-item">Kommentare:

                {% if user.is_authenticated %}
                <br clear="all"/>
                <p>
                {% load crispy_forms_tags %}
                    <form method="post" action="{% url 'smallads:smallad_comment_create' smallad.id %}">
                        {% csrf_token %}
                        {{ comment_form|crispy }}
                    <input type="submit" value="Submit">
                    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'smallads:all' %}';return false;">
                    </form>
                </p>
                {% endif %}

                {% for comment in comments %}
                <p>{{ comment.owner }}: {{ comment.text }}
                ({{ comment.updated_at|naturaltime }})
                {% if user == comment.owner %}
                    <a href="{% url 'smallads:smallad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
                {% endif %}
                </p>
                {% endfor %}

            </li>
          </ul>
          <div class="card-body">
            <a href="#" class="card-link">Auf meine Wunschliste</a>
            <a href="{% url 'smallads:all' %}" class="card-link">Alle Kleinanzeigen</a>
          </div>
        </div>
    </div>
</div>
</div>

<script>
    function favAd(url, smallad_id) {
        console.log('Requesting JSON');
        $.post(url, {},  function(rowz){
            console.log(url, 'finished');
            $("#unfavorite_star_"+smallad_id).toggle();
            $("#favorite_star_"+smallad_id).toggle();
        }).fail(function(xhr) {
            alert('Url failed with '+xhr.status+' '+url);
        });
    }
</script>

{% endblock %}

mysite/smallads/templates/smallads/smallad_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Kleinanzeigen - Eingabeformular{% endblock %}

{% block content %}

<div class="m-5">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <a href="{% url 'smallads:all' %}" class="btn btn-dark my-3">Go Back</a>
                <div class="card">
                    <div class="card-header">Kleinanzeige anlegen oder ändern</div>

                      <form action="" method="post" id="upload_form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group m-3">
                            <label>Titel</label>
                            <input required name="title" type="text" placeholder="Gib einen Titel ein"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Preis</label>
                            <input required name="price" type="text" placeholder="Preis in Euro"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Beschreibung</label>
                            <input required name="description" type="text" placeholder="Sag etwas Besonderes über dein Produkt..."
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Select a category</label>
                            <select name="category" class="form-control">
                                <option value='none'>Select a category...</option>

                                {% for category in categories %}
                                <option value='{{category.id}}'>{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group m-3">
                            <label>Kategorie anlegen</label>
                            <input name="category_new" type="text" placeholder="Neue Kategorie oder frei lassen bei obiger Auswahl..."
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Tags</label>
                            <input name="tags" type="text" placeholder="durch Kommas getrennte Schlagwortliste, mehrere Worte in Anführungen..."
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Foto hochladen</label>
                            <input required name="image" type="file" class="form-control-file">
                        </div>

                        <button type='submit' class="btn btn-primary my-3">Submit</button>
                        <button class="btn btn-primary my-3" type="submit" value="Cancel" onclick="window.location.href='{% url 'smallads:all' %}';return false;">Cancel</button>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
    console.log('Checking file size');
    if (window.File && window.FileReader && window.FileList && window.Blob) {
        var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
        if file && file.size > {{ form.max_upload_limit }} ) {
            alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
        return false;
        }
    }
});
</script>
{% endblock %}

mysite/smallads/templates/smallads/smallad_list.html
{% extends 'base.html' %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block title %}Gallery of classifieds{% endblock %}

{% block head %}
<!-- das brauchen wir eigentlich nicht, weil ich doch keine w3 school Klassen in base.html verwende-->
<style>

    * {
        box-sizing: border-box;
    }
    form.ad_list_search_form input[type=text] {
      padding: 10px;
      font-size: 17px;
      border: 1px solid teal;
      float: left;
      width: 80%;
      background: #f1f1f1;
    }

    form.ad_list_search_form button {
      float: left;
      width: 20%;
      padding: 10px;
      background: #2196F3;
      color: white;
      font-size: 17px;
      border: 1px solid teal;
      border-left: none;
      cursor: pointer;
    }

    form.ad_list_search_form button:hover {
      background: #0b7dda;
    }

    form.ad_list_search_form::after {
      content: "";
      clear: both;
      display: table;
    }

    .image-thumbnail {
            height: 200px;
            object-fit: cover;
    }

    .list-group-item a {
            text-decoration: none;
            color: black;
    }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <h1 class="herotitle">Kleinanzeigen</h1>

    <div class="m-5">
    <!--
        <div style="float:right">
        <!-- https://www.w3schools.com/howto/howto_css_search_button.asp-->
    <!--    <form class="ad_list_search_form">
            <input type="text" placeholder="Search.." name="search" pattern=".{3,}"  required title="3 characters minimum"
            {% if search %} value="{{ search }}" {% endif %}>
            <button type="submit"><i class="fa fa-search"></i></button>
            <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
        </form>
        </div>
    -->
        <div class="row justify-content-center">
            <div class="col-md-3">
            {% if request.user.is_authenticated %}
                <p>Hello {{request.user}}</p>
            {% endif %}

                <!-- Diese Karte zeigt die Kategorien -->
                <div class="card my-2">
                        <div class="card-header">Kategorien</div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <a href="{% url 'smallads:all' %}">Alle Kategorien</a>
                            </li>
                            {% if category_list %}
                                {% for category in category_list %}
                                    <li class=" list-group-item">
                                        <a href="{% url 'smallads:all' %}?category={{category.name}}">
                                        {{category.name}}
                                        </a>
                                    </li>
                                {% endfor %}
                            {% else %}
                                <p>Noch keine Kategorien angelegt.</p>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <a href="{% url 'smallads:smallad_create' %}" class="btn btn-dark btn-block btn-sm m-1">Neue Kleinanzeige</a>
                                <a href="{% url 'logout' %}?next={% url 'smallads:all' %}" class="btn btn-dark btn-block btn-sm m-1">Logout</a>
                            {% else %}
                                <a href="{% url 'login' %}?next={% url 'smallads:all' %}" class="btn btn-dark btn-block btn-sm m-1">Login</a>
                            {% endif %}

                        </ul>

                        {% if request.user.is_authenticated %}
                            <hr>
                            <p>{{ user }}, du magst {{ fav_count }} Kleinanzeigen: </p>
                            <ol>
                                {% for fav in favorites %}
                                    <li>{{ fav }}</li>
                                {% empty %}
                                    <p>{{ user }} hat noch keine Favoriten.</p>
                                {% endfor %}
                            </ol>
                        {% endif %}

                </div>
            </div>

            <!-- Diese col zeigen die Kleinanzeigen -->
            <div class="col-md-9">
                <div class="row">
                {% for smallad in smallad_list %}
                    <div class="col-md-4">
                        <div class="card my-2">
                            <img class="image-thumbnail" src="{{smallad.image.url}}" alt="Card image cap">

                            <div class="card-body">
                                <small>Category: {{smallad.category.name}}</small></br>
                                <a href="{% url 'smallads:smallad_detail'  smallad.id %}">{{ smallad.title|truncatechars:20 }}</a></br>
                                <small>Preis: {{smallad.price}} Euro</small></br>
                                <small>=> {{smallad.description|truncatechars:20}}...</small></br>

                                <!-- Achtung: total ist ein Pseudofeld (.annotate), was nicht im Model zu finden ist -->
                                <small>{{smallad.total}} User lieben diesen Artikel.</small></br>

                                <!--hier die kleinen Sterne einbauen -->
                                <!--1. Schritt: für alle visitor als Summe anschauen-->
                                <!-- for fav in ... oder if fav in favorites ....-->
                                {% for i in fav_counter %}
                                <span class="fa-stack" style="vertical-align: middle;">
                                    <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                                    <i class="fa fa-star-o fa-stack-1x"></i>
                                </span>
                                {% endfor %}
                            </div>
                            <a href="{% url 'smallads:smallad_detail' smallad.id %}" class="btn btn-outline-dark btn-sm m-1">View...</a>
                        </div>
                    </div>
                {% empty %}
                    <h3>Keine Kleinanzeigen in der Datenbank...</h3>
                {% endfor %}

                </div>
            </div>
        </div>
        <!--
        <div class="row">
            <ul>
            {% for fav in smalladfav_list %}
            <li>{{ fav }}</li>
            {% endfor %}
            </ul>
        </div>
        -->

    </div>
</div>
{% endblock %}